In [1]:
from google.colab import drive

In [2]:

drive.mount ('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/"MyDrive/machine learning /machine-learning-master"

/content/drive/MyDrive/machine learning /machine-learning-master


In [4]:

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


In [5]:
dataset = pd.read_csv("predictive_maintenance.csv")


In [6]:
dataset

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target  \
0                       1551         42.8                0       0   
1                       1408         46.3                3       0   
2                       1498         49.4                5       0   
3                       1433         39.5                7       0   
4                       1408         40.0                9       0   
...                      ...          ...              ...     ...   
9995                    1604         29.5               14       0   
9996                    1632         31.8               17       0   
9997                    1645         33.4               22       0   
9998                    1408         48.5               25       0   
9999                    1500         40.2               30       0   

     Failure Type  
0      No Failure  
1      No Failure  
2      No Failure  
3      No Failure  
4      No Failure  
...           ...  
9995   No Failure  
9996   No Failure  
9997   No Failure  
9998   No Failure  
9999   No Failure  

[10000 rows x 10 columns]

In [7]:
type(dataset)

pandas.core.frame.DataFrame

In [8]:
dataf=pd.DataFrame(dataset)

In [9]:
dataf.describe()

UDI  Air temperature [K]  Process temperature [K]  \
count  10000.00000         10000.000000             10000.000000   
mean    5000.50000           300.004930               310.005560   
std     2886.89568             2.000259                 1.483734   
min        1.00000           295.300000               305.700000   
25%     2500.75000           298.300000               308.800000   
50%     5000.50000           300.100000               310.100000   
75%     7500.25000           301.500000               311.100000   
max    10000.00000           304.500000               313.800000   

       Rotational speed [rpm]   Torque [Nm]  Tool wear [min]        Target  
count            10000.000000  10000.000000     10000.000000  10000.000000  
mean              1538.776100     39.986910       107.951000      0.033900  
std                179.284096      9.968934        63.654147      0.180981  
min               1168.000000      3.800000         0.000000      0.000000  
25%               1423.000000     33.200000        53.000000      0.000000  
50%               1503.000000     40.100000       108.000000      0.000000  
75%               1612.000000     46.800000       162.000000      0.000000  
max               2886.000000     76.600000       253.000000      1.000000

In [10]:
Air_temperature_value=dataf.iloc[0:10000,3:4]
Process_temperature_value=dataf.iloc[0:10000,4:5]
Rotational_speed_value=dataf.iloc[0:10000,5:6]
Torque_value=dataf.iloc[0:10000,6:7]
Tool_wear_value=dataf.iloc[0:10000,7:8]
Target_value=dataf.iloc[0:10000,8:9]

In [11]:
Air_temperature_value

Air temperature [K]
0                   298.1
1                   298.2
2                   298.1
3                   298.2
4                   298.2
...                   ...
9995                298.8
9996                298.9
9997                299.0
9998                299.0
9999                299.0

[10000 rows x 1 columns]

In [12]:
 Process_temperature_value

Process temperature [K]
0                       308.6
1                       308.7
2                       308.5
3                       308.6
4                       308.7
...                       ...
9995                    308.4
9996                    308.4
9997                    308.6
9998                    308.7
9999                    308.7

[10000 rows x 1 columns]

In [13]:
Rotational_speed_value

Rotational speed [rpm]
0                       1551
1                       1408
2                       1498
3                       1433
4                       1408
...                      ...
9995                    1604
9996                    1632
9997                    1645
9998                    1408
9999                    1500

[10000 rows x 1 columns]

In [14]:
Torque_value

Torque [Nm]
0            42.8
1            46.3
2            49.4
3            39.5
4            40.0
...           ...
9995         29.5
9996         31.8
9997         33.4
9998         48.5
9999         40.2

[10000 rows x 1 columns]

In [15]:
Tool_wear_value

Tool wear [min]
0                   0
1                   3
2                   5
3                   7
4                   9
...               ...
9995               14
9996               17
9997               22
9998               25
9999               30

[10000 rows x 1 columns]

In [16]:
Target_value

Target
0          0
1          0
2          0
3          0
4          0
...      ...
9995       0
9996       0
9997       0
9998       0
9999       0

[10000 rows x 1 columns]

In [17]:
dataf = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
dataf.drop(["Product ID", "Type"], axis = 1, inplace = True)

dataf

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
UDI                                                                           
1                    298.1                    308.6                    1551   
2                    298.2                    308.7                    1408   
3                    298.1                    308.5                    1498   
4                    298.2                    308.6                    1433   
5                    298.2                    308.7                    1408   
...                    ...                      ...                     ...   
9996                 298.8                    308.4                    1604   
9997                 298.9                    308.4                    1632   
9998                 299.0                    308.6                    1645   
9999                 299.0                    308.7                    1408   
10000                299.0                    308.7                    1500   

       Torque [Nm]  Tool wear [min]  Target Failure Type  
UDI                                                       
1             42.8                0       0   No Failure  
2             46.3                3       0   No Failure  
3             49.4                5       0   No Failure  
4             39.5                7       0   No Failure  
5             40.0                9       0   No Failure  
...            ...              ...     ...          ...  
9996          29.5               14       0   No Failure  
9997          31.8               17       0   No Failure  
9998          33.4               22       0   No Failure  
9999          48.5               25       0   No Failure  
10000         40.2               30       0   No Failure  

[10000 rows x 7 columns]

In [18]:
dataf=pd.get_dummies(dataf)
dataf

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
UDI                                                                           
1                    298.1                    308.6                    1551   
2                    298.2                    308.7                    1408   
3                    298.1                    308.5                    1498   
4                    298.2                    308.6                    1433   
5                    298.2                    308.7                    1408   
...                    ...                      ...                     ...   
9996                 298.8                    308.4                    1604   
9997                 298.9                    308.4                    1632   
9998                 299.0                    308.6                    1645   
9999                 299.0                    308.7                    1408   
10000                299.0                    308.7                    1500   

       Torque [Nm]  Tool wear [min]  Target  \
UDI                                           
1             42.8                0       0   
2             46.3                3       0   
3             49.4                5       0   
4             39.5                7       0   
5             40.0                9       0   
...            ...              ...     ...   
9996          29.5               14       0   
9997          31.8               17       0   
9998          33.4               22       0   
9999          48.5               25       0   
10000         40.2               30       0   

       Failure Type_Heat Dissipation Failure  Failure Type_No Failure  \
UDI                                                                     
1                                          0                        1   
2                                          0                        1   
3                                          0                        1   
4                                          0                        1   
5                                          0                        1   
...                                      ...                      ...   
9996                                       0                        1   
9997                                       0                        1   
9998                                       0                        1   
9999                                       0                        1   
10000                                      0                        1   

       Failure Type_Overstrain Failure  Failure Type_Power Failure  \
UDI                                                                  
1                                    0                           0   
2                                    0                           0   
3                                    0                           0   
4                                    0                           0   
5                                    0                           0   
...                                ...                         ...   
9996                                 0                           0   
9997                                 0                           0   
9998                                 0                           0   
9999                                 0                           0   
10000                                0                           0   

       Failure Type_Random Failures  Failure Type_Tool Wear Failure  
UDI                                                                  
1                                 0                               0  
2                                 0                               0  
3                                 0                               0  
4                                 0                               0  
5                                 0                               0  
...             

In [19]:

dataf.shape

(10000, 12)

In [20]:

labels=np.array(dataf['Failure Type_Heat Dissipation Failure'])

In [21]:
dataf=dataf.drop('Failure Type_Heat Dissipation Failure',axis=1)

In [22]:
labels

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [23]:
dataf

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
UDI                                                                           
1                    298.1                    308.6                    1551   
2                    298.2                    308.7                    1408   
3                    298.1                    308.5                    1498   
4                    298.2                    308.6                    1433   
5                    298.2                    308.7                    1408   
...                    ...                      ...                     ...   
9996                 298.8                    308.4                    1604   
9997                 298.9                    308.4                    1632   
9998                 299.0                    308.6                    1645   
9999                 299.0                    308.7                    1408   
10000                299.0                    308.7                    1500   

       Torque [Nm]  Tool wear [min]  Target  Failure Type_No Failure  \
UDI                                                                    
1             42.8                0       0                        1   
2             46.3                3       0                        1   
3             49.4                5       0                        1   
4             39.5                7       0                        1   
5             40.0                9       0                        1   
...            ...              ...     ...                      ...   
9996          29.5               14       0                        1   
9997          31.8               17       0                        1   
9998          33.4               22       0                        1   
9999          48.5               25       0                        1   
10000         40.2               30       0                        1   

       Failure Type_Overstrain Failure  Failure Type_Power Failure  \
UDI                                                                  
1                                    0                           0   
2                                    0                           0   
3                                    0                           0   
4                                    0                           0   
5                                    0                           0   
...                                ...                         ...   
9996                                 0                           0   
9997                                 0                           0   
9998                                 0                           0   
9999                                 0                           0   
10000                                0                           0   

       Failure Type_Random Failures  Failure Type_Tool Wear Failure  
UDI                                                                  
1                                 0                               0  
2                                 0                               0  
3                                 0                               0  
4                                 0                               0  
5                                 0                               0  
...                             ...                             ...  
9996                              0                               0  
9997                              0                               0  
9998                              0                               0  
9999                              0                               0  
10000                             0                               0  

[10000 rows x 11 columns]

In [24]:
dataf_list=list(dataf.columns)
dataf=np.array(dataf)

In [25]:
dataf

array([[ 298.1,  308.6, 1551. , ...,    0. ,    0. ,    0. ],
       [ 298.2,  308.7, 1408. , ...,    0. ,    0. ,    0. ],
       [ 298.1,  308.5, 1498. , ...,    0. ,    0. ,    0. ],
       ...,
       [ 299. ,  308.6, 1645. , ...,    0. ,    0. ,    0. ],
       [ 299. ,  308.7, 1408. , ...,    0. ,    0. ,    0. ],
       [ 299. ,  308.7, 1500. , ...,    0. ,    0. ,    0. ]])

In [26]:


dataf_list

['Air temperature [K]',
 'Process temperature [K]',
 'Rotational speed [rpm]',
 'Torque [Nm]',
 'Tool wear [min]',
 'Target',
 'Failure Type_No Failure',
 'Failure Type_Overstrain Failure',
 'Failure Type_Power Failure',
 'Failure Type_Random Failures',
 'Failure Type_Tool Wear Failure']

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
train_dataf,test_dataf,train_labels,test_labels=train_test_split(dataf,labels,test_size=0.25,random_state=42)

In [29]:
test_labels.shape

(2500,)

In [30]:
test_dataf.shape

(2500, 11)

In [31]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
rf=RandomForestRegressor(n_estimators=1000,random_state=42)

In [33]:
rf.fit(train_dataf,train_labels) 

RandomForestRegressor(n_estimators=1000, random_state=42)

In [34]:
predections=rf.predict(test_dataf)

In [35]:
test_labels.shape

(2500,)

In [36]:
predections

array([0.   , 0.019, 0.   , ..., 0.   , 0.   , 0.   ])

In [37]:
new_predections = predections.astype(int)
print(new_predections)

[0 0 0 ... 0 0 0]


In [38]:
new_predections.reshape(-1, 1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

add loop to compare and find the error 


In [39]:
new_predections.shape

(2500,)

In [40]:
test_labels

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [41]:
new_test_labels =test_labels.astype(int)
print(new_test_labels)

[0 0 0 ... 0 0 0]


In [42]:
new_test_labels.reshape(-1, 1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [43]:
from sklearn.metrics import accuracy_score
print(" accuracy of heat dissipation : {} ".format(accuracy_score(new_test_labels, new_predections)))

 accuracy of heat dissipation : 0.9936 
