In [18]:
from google.colab import drive



In [19]:
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
cd /content/drive/"MyDrive/machine learning /machine-learning-master"

/content/drive/MyDrive/machine learning /machine-learning-master


In [21]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


In [22]:

dataset = pd.read_csv("predictive_maintenance.csv")


In [23]:


dataset

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target  \
0                       1551         42.8                0       0   
1                       1408         46.3                3       0   
2                       1498         49.4                5       0   
3                       1433         39.5                7       0   
4                       1408         40.0                9       0   
...                      ...          ...              ...     ...   
9995                    1604         29.5               14       0   
9996                    1632         31.8               17       0   
9997                    1645         33.4               22       0   
9998                    1408         48.5               25       0   
9999                    1500         40.2               30       0   

     Failure Type  
0      No Failure  
1      No Failure  
2      No Failure  
3      No Failure  
4      No Failure  
...           ...  
9995   No Failure  
9996   No Failure  
9997   No Failure  
9998   No Failure  
9999   No Failure  

[10000 rows x 10 columns]

In [24]:
type(dataset)

pandas.core.frame.DataFrame

In [25]:
#from sklearn.svm import LinearSVC
#SVC = LinearSVC().fit(X_train,y_train)
#y_predsvm = SVC.predict(X_test)
#print(confusion_matrix(y_predsvm,y_test))

In [33]:
#dataf = datafTarget

datafTarget=pd.DataFrame(dataset)

y = datafTarget["Target"].values
datafTarget = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
datafTarget.drop(["Product ID","Target"], axis = 1, inplace = True)

datafTarget=pd.get_dummies(datafTarget)

x = (datafTarget - np.min(datafTarget))/(np.max(datafTarget)-np.min(datafTarget))
#over sampling
from imblearn.over_sampling import RandomOverSampler
rus=RandomOverSampler(sampling_strategy=1)
x_res,y_res = rus.fit_resample(x,y)
#ax=y_res.value_counts().plot.pie(autopct='%.2f')
#_=ax.set_title("over sampling")
# train test split
# train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_res,y_res,test_size = 0.3,random_state=1)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
SVC = LinearSVC().fit(x_train,y_train)
y_predsvm = SVC.predict(x_test)
print(" score of target : {} ".format(SVC.score(x_test,y_test)))
print(confusion_matrix(y_predsvm,y_test))
print(classification_report(y_predsvm,y_test))
#from sklearn.neighbors import KNeighborsClassifier
#knn = KNeighborsClassifier(n_neighbors = 3) # n_neighbors = k
#knn.fit(x_train,y_train)
#prediction = knn.predict(x_test)
#print(" score target : {} ".format(knn.score(x_test,y_test)))

#y_pred = knn.predict(x_test)
#y_true=y_test



#cm vizualization

#import seaborn as sns 
#f, ax =plt.subplots(figsize = (5,5))

#sns.heatmap(cm,annot = True, linewidths= 0.5, linecolor="cyan", fmt=".0f", ax=ax)
#plt.xlabel("y_pred")
#plt.ylabel("y_true")
#plt.show()

#performance parameter 

#print(classification_report(y_pred,y_true))

 score of target : 0.9894773158530275 
[[2942   61]
 [   0 2794]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99      3003
           1       0.98      1.00      0.99      2794

    accuracy                           0.99      5797
   macro avg       0.99      0.99      0.99      5797
weighted avg       0.99      0.99      0.99      5797



In [34]:
datafheat=pd.DataFrame(dataset)
datafheat = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
datafheat.drop(["Product ID","Target"], axis = 1, inplace = True)

datafheat=pd.get_dummies(datafheat)

y1 = datafheat["Failure Type_Heat Dissipation Failure"].values
x1 = (datafheat - np.min(datafheat))/(np.max(datafheat)-np.min(datafheat))
#over sampling
from imblearn.over_sampling import RandomOverSampler
rus=RandomOverSampler(sampling_strategy=1)
x_resh,y_resh = rus.fit_resample(x1,y1)
#ax=y_res.value_counts().plot.pie(autopct='%.2f')
#_=ax.set_title("over sampling")
# train test split
from sklearn.model_selection import train_test_split
x_train1, x_test1, y_train1, y_test1 = train_test_split(x_resh,y_resh,test_size = 0.3,random_state=1)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
SVC1 = LinearSVC().fit(x_train1,y_train1)
y_predsvm1 = SVC.predict(x_test1)
print(" score of heat : {} ".format(SVC1.score(x_test1,y_test1)))
print(confusion_matrix(y_predsvm1,y_test1))
print(classification_report(y_predsvm1,y_test1))

 score of heat : 1.0 
[[2948    0]
 [  57 2928]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2948
           1       1.00      0.98      0.99      2985

    accuracy                           0.99      5933
   macro avg       0.99      0.99      0.99      5933
weighted avg       0.99      0.99      0.99      5933



In [35]:
datafover=pd.DataFrame(dataset)

datafover = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
datafover.drop(["Product ID","Target"], axis = 1, inplace = True)

datafover=pd.get_dummies(datafover)
y2 = datafover["Failure Type_Overstrain Failure"].values
x2 = (datafover - np.min(datafover))/(np.max(datafover)-np.min(datafover))
#oversampling
from imblearn.over_sampling import RandomOverSampler
rus=RandomOverSampler(sampling_strategy=1)
x_resO,y_resO = rus.fit_resample(x2,y2)
#ax=y_res.value_counts().plot.pie(autopct='%.2f')
#_=ax.set_title("over sampling")
# train test split
from sklearn.model_selection import train_test_split
x_train2, x_test2, y_train2, y_test2 = train_test_split(x_resO,y_resO,test_size = 0.3,random_state=1)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC


SVC2 = LinearSVC().fit(x_train2,y_train2)
y_predsvm2 = SVC.predict(x_test2)
print(" score of overstrain : {} ".format(SVC2.score(x_test2,y_test2)))
print(confusion_matrix(y_predsvm2,y_test2))
print(classification_report(y_predsvm2,y_test2))

 score of overstrain : 1.0 
[[2930    0]
 [  81 2943]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99      2930
           1       1.00      0.97      0.99      3024

    accuracy                           0.99      5954
   macro avg       0.99      0.99      0.99      5954
weighted avg       0.99      0.99      0.99      5954



In [36]:
datafpower=pd.DataFrame(dataset)

datafpower = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
datafpower.drop(["Product ID","Target"], axis = 1, inplace = True)

datafpower=pd.get_dummies(datafpower)
y3 = datafpower["Failure Type_Power Failure"].values
x3 = (datafpower - np.min(datafpower))/(np.max(datafpower)-np.min(datafpower))
#oversampling
from imblearn.over_sampling import RandomOverSampler
rus=RandomOverSampler(sampling_strategy=1)
x_resp,y_resp = rus.fit_resample(x3,y3)
#ax=y_res.value_counts().plot.pie(autopct='%.2f')
#_=ax.set_title("over sampling")
# train test split
# train test split
from sklearn.model_selection import train_test_split
x_train3, x_test3, y_train3, y_test3 = train_test_split(x_resp,y_resp,test_size = 0.3,random_state=1)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
SVC3 = LinearSVC().fit(x_train3,y_train3)
y_predsvm3 = SVC.predict(x_test3)
print(" score of power failure : {} ".format(SVC3.score(x_test3,y_test3)))
print(confusion_matrix(y_predsvm3,y_test3))
print(classification_report(y_predsvm3,y_test3))

 score of power failure : 1.0 
[[2937    0]
 [  71 2935]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2937
           1       1.00      0.98      0.99      3006

    accuracy                           0.99      5943
   macro avg       0.99      0.99      0.99      5943
weighted avg       0.99      0.99      0.99      5943



In [38]:
datafran=pd.DataFrame(dataset)


datafran = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
datafran.drop(["Product ID","Target"], axis = 1, inplace = True)

datafran=pd.get_dummies(datafran)

y4 = datafran["Failure Type_Random Failures"].values
x4 = (datafran - np.min(datafran))/(np.max(datafran)-np.min(datafran))
#oversampling
from imblearn.over_sampling import RandomOverSampler
rus=RandomOverSampler(sampling_strategy=1)
x_resr,y_resr = rus.fit_resample(x4,y4)
#ax=y_res.value_counts().plot.pie(autopct='%.2f')
#_=ax.set_title("over sampling")
# train test split
# train test split
from sklearn.model_selection import train_test_split
x_train4, x_test4, y_train4, y_test4 = train_test_split(x_resr,y_resr,test_size = 0.3,random_state=1)


from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
SVC4 = LinearSVC().fit(x_train4,y_train4)
y_predsvm4 = SVC.predict(x_test4)
print(" score of random failure : {} ".format(SVC4.score(x_test4,y_test4)))
print(confusion_matrix(y_predsvm4,y_test4))
print(classification_report(y_predsvm4,y_test4))

 score of random failure : 1.0 
[[2946 2947]
 [  97    0]]
              precision    recall  f1-score   support

           0       0.97      0.50      0.66      5893
           1       0.00      0.00      0.00        97

    accuracy                           0.49      5990
   macro avg       0.48      0.25      0.33      5990
weighted avg       0.95      0.49      0.65      5990



In [39]:
dataftool=pd.DataFrame(dataset)

dataftool = pd.read_csv("predictive_maintenance.csv", index_col ="UDI" )
dataftool.drop(["Product ID","Target"], axis = 1, inplace = True)

dataftool=pd.get_dummies(dataftool)
y5 = dataftool["Failure Type_Tool Wear Failure"].values
x5 = (dataftool- np.min(dataftool))/(np.max(dataftool)-np.min(dataftool))
#over sampling
from imblearn.over_sampling import RandomOverSampler
rus=RandomOverSampler(sampling_strategy=1)
x_rest,y_rest = rus.fit_resample(x5,y5)
#ax=y_res.value_counts().plot.pie(autopct='%.2f')
#_=ax.set_title("over sampling")
# train test split
from sklearn.model_selection import train_test_split
x_train5, x_test5, y_train5, y_test5 = train_test_split(x_rest,y_rest,test_size = 0.3,random_state=1)


from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
SVC5 = LinearSVC().fit(x_train5,y_train5)
y_predsvm5 = SVC.predict(x_test5)
print(" score of toolwear failure : {} ".format(SVC5.score(x_test5,y_test5)))
print(confusion_matrix(y_predsvm5,y_test5))
print(classification_report(y_predsvm5,y_test5))

 score of toolwear failure : 1.0 
[[2978    0]
 [  89 2906]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99      2978
           1       1.00      0.97      0.98      2995

    accuracy                           0.99      5973
   macro avg       0.99      0.99      0.99      5973
weighted avg       0.99      0.99      0.99      5973

